# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cek Ongkir' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cek Ongkir
  pod 'Material', '~> 2.0'

  target 'Cek OngkirTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Cek OngkirUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
